-- Habilita el uso de claves foráneas en SQLite (importante)
PRAGMA foreign_keys = ON;

-- 1. TABLA DE PACIENTES
CREATE TABLE IF NOT EXISTS PACIENTES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    edad INTEGER,
    sexo TEXT,
    contacto TEXT
);

-- 2. TABLA DE DOCTORES
CREATE TABLE IF NOT EXISTS DOCTORES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    sala_id INTEGER,
    disponible INTEGER DEFAULT 1
);

-- 3. TABLA DE TRABAJADORES SOCIALES
CREATE TABLE IF NOT EXISTS TRABAJADORES_SOCIALES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    sala_id INTEGER,
    activo INTEGER DEFAULT 1
);

-- 4. TABLA DE CAMAS DE ATENCIÓN
CREATE TABLE IF NOT EXISTS CAMAS_ATENCION (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    numero INTEGER NOT NULL,
    sala_id INTEGER NOT NULL,
    ocupada INTEGER DEFAULT 0,
    paciente_id INTEGER,
    
    FOREIGN KEY (paciente_id) REFERENCES PACIENTES(id)
);

-- 5. TABLA DE VISITAS DE EMERGENCIA
CREATE TABLE IF NOT EXISTS VISITAS_EMERGENCIA (
    folio TEXT PRIMARY KEY,
    paciente_id INTEGER NOT NULL,
    doctor_id INTEGER,
    cama_id INTEGER,
    trabajador_social_id INTEGER,
    sala_id INTEGER NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    estado TEXT,
    
    FOREIGN KEY (paciente_id) REFERENCES PACIENTES(id),
    FOREIGN KEY (doctor_id) REFERENCES DOCTORES(id),
    FOREIGN KEY (cama_id) REFERENCES CAMAS_ATENCION(id),
    FOREIGN KEY (trabajador_social_id) REFERENCES TRABAJADORES_SOCIALES(id)
);

-- 6. TABLA DE USUARIOS DEL SISTEMA
CREATE TABLE IF NOT EXISTS USUARIOS_SISTEMA (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    rol TEXT NOT NULL,
    id_personal INTEGER
);
